### ISSUE TITLE
Add capture node name for freeswitch native capture agent

### ISSUE THREAD

**Issue by hnimminh** [sipcapture/homer#551] opened 2022-08-02 03:30 UTC
Hi @lmangani , I'm trying to add support nodename to header
some how it doesn't work, I try to find out but no luck, can you help by take a look into this:
https://github.com/freeswitch/sofia-sip/compare/master...hnimminh:sofia-sip:homer-capture-support-nodename

very appreciate !

**Comment by kYroL01** [comment] 2022-10-12 16:43
Hi @hnimminh . 
I see the link refers to a PR you want to send, correct ? 
The code seems correct at a first sight, but I need to double-check before giving you a correct answer.
It also must be checked as we parse that in Homer.
We will recheck and let you know.

Thanks

**Comment by lmangani** [comment] 2022-10-12 20:52
I'm not at all familiar with the FS code perhaps @adubovikov could you take a look and make a suggestion?

**Comment by kYroL01** [comment] 2022-10-17 09:12
Hi @hnimminh the modification in your first answer are correct, as I review with @adubovikov .
Feel free to forward that PR to freeswitch .
Thank you

**Comment by hnimminh** [comment] 2022-10-18 03:44
Thanks @kYroL01 @adubovikov @lmangani for your help.
May I know the reason why message (send by above modification) was not show on homer, is this bug of parser in Homer?

**Comment by kYroL01** [comment] 2022-10-18 07:48
Hi @hnimminh . Not a bug. Homer has the possibility to parse and show capture-id as a name, but it's sent as a HEP information from an agent (`heplify` for example). 
Now if FS accept your PR you will see your capture-id as a string ;)

I will close this issue. In case of problems feel free to reopen

Thank you!

**Closed as completed by kYroL01** 2022-10-18 07:48 UTC
Labels: Testing Needed, in progress, help wanted, stargazed
