### ISSUE TITLE
Talk Duration is zero and Ringing Time the whole call?

### ISSUE THREAD

**Issue by heig** [sipcapture/homer#475] opened 2021-07-31 15:17 UTC
Hi everybody, 
I installed homer using the Docker-image today and started with a few test calls to test it out. 

However in the "Session Info" I see that the Ringing Time shows nearly the time of the whole call and the "Talk Duration" is 00:00:00. But since I was on the phone with myself, I know that some talking happend :) 

![image](https://user-images.githubusercontent.com/8817380/127744395-89c59203-a0c6-4227-b841-9c0590d4d208.png)

Do you need any futher information or is this a config issue? 

Thanks!

**Comment by lmangani** [comment] 2021-07-31 15:33
This would suggest a 200 OK after a 180/183 was missed, but we can't help without seeing the full session message stack.

**Comment by heig** [comment] 2021-07-31 15:37
Hm, from what I can see, it looks like this is okay. 183 -> 180 -> 200
![image](https://user-images.githubusercontent.com/8817380/127744993-1470430f-304b-48d8-b1c8-b6126831031d.png)

Here is the full TXT Export. 

[export_65.txt](https://github.com/sipcapture/homer/files/6911405/export_65.txt)

**Comment by lmangani** [comment] 2021-07-31 15:55
This could be due to the 183 + 180 in the same session. We'll try to reproduce and confirm if this is indeed the case.

**Comment by heig** [comment] 2021-07-31 15:56
thank you very much. If you need more details, please let me know!

**Comment by adubovikov** [comment] 2021-08-01 11:47
fixed in the dev branch
https://github.com/sipcapture/homer-ui/commit/b6fe6ad3dfe5256df3b4609f22a89f0b3d7ddbcc

you can pull or just wait for a new release.

**Comment by adubovikov** [comment] 2021-08-05 07:15
fixed in the release. Please test it and reopen ticket if needed.

**Closed as completed by adubovikov** 2021-08-05 07:15 UTC
