### ISSUE TITLE
Adding Nodes does not Work

### ISSUE THREAD

**Issue by lylepratt** [sipcapture/homer#123] opened 2015-12-11 22:45 UTC
Adding a node in the "System Admin" pane does not work. No error is returned. The JSON returned by the HTTP request does not include the new node.

**Comment by lmangani** [comment] 2015-12-11 22:47
Could you check if any php logs are generated during the insert attempt?

**Comment by thomasquintana** [comment] 2015-12-11 22:55
PHP logs are empty :(

```
[11-Dec-2015 00:47:28] NOTICE: fpm is running, pid 2689
[11-Dec-2015 00:47:28] NOTICE: ready to handle connections
[11-Dec-2015 00:47:28] NOTICE: systemd monitor interval set to 10000ms
```

**Comment by thomasquintana** [comment] 2015-12-11 22:56
That actually makes sense since we're not getting an error back. Just a 200 with the original entries in it.

**Comment by lmangani** [comment] 2015-12-11 23:10
Cannot replicate so far. Could you provide the full setup specs including software versions in use please.

**Comment by thomasquintana** [comment] 2015-12-11 23:20
Okay so after testing this is what I found. It didn't add the new node because there was already a node with a host of `localhost`. I think it may be helpful to have an alert letting the users know that a node for host x already exists so the user doesn't think that it either doesn't work or he/she is doing something wrong.

Thank you so much for all your help yesterday and today @lmangani. We will keep testing and reporting anything unexpected behavior we encounter. Have a great weekend! :)

**Comment by thomasquintana** [comment] 2015-12-11 23:21
@lylepratt Can you please close this ticket.

**Comment by lmangani** [comment] 2015-12-11 23:21
Excellent finding and good point - we will extend the response to report the exception more clearly.

**Closed by lmangani** 2015-12-11 23:21 UTC
