### ISSUE TITLE
initial login to homer 7 UI

### ISSUE THREAD

**Issue by shchbo** [sipcapture/homer#463] opened 2021-04-21 09:33 UTC
after installing homer 7 using install script on centos 7 the initial login to UI using admin/sipcapture returns "wrong password" error.
is it possible to change it in the DB somewhere so i can start working with homer?

**Comment by lmangani** [comment] 2021-04-21 10:41
hello @shchbo 
as you positive your db is up and running? did you keep any installation logs?

**Comment by shchbo** [comment] 2021-04-21 10:52
the db is up and running. i installed homer using the same script a few times before and it never happened to me.
 i am afraid i dont have the installation logs.

**Comment by lmangani** [comment] 2021-04-21 12:10
just ran a vanilla setup and everything works as expected. you can use `homer-app` to perform basic maintenance including resetting users. give that a try and let us know
```
# homer-app -h
```

**Comment by shchbo** [comment] 2021-04-22 06:04
is it possible to update the user 'admin' for UI with new password like this:
homer-app -update-ui-user  admin -update-ui-password sipcapture
it returns 
{"level":"info","msg":"Connecting to the config: [localhost, homer_user, homer_config, 0]\n","time":"2021-04-22T09:04:06+03:00"}
{"level":"info","msg":"----------------------------------- ","time":"2021-04-22T09:04:06+03:00"}
{"level":"info","msg":"*** Database Config Session created *** ","time":"2021-04-22T09:04:06+03:00"}
{"level":"info","msg":"----------------------------------- ","time":"2021-04-22T09:04:06+03:00"}
{"level":"info","msg":"Updating password for user: [admin]\n","time":"2021-04-22T09:04:06+03:00"}
Succesful ping: localhost, Type: config, Node: localnode{"level":"debug","msg":"56 \u003cnil\u003e","time":"2021-04-22T09:04:06+03:00"}
{"level":"info","module":"gorm","msg":"SELECT * FROM \"users\"  WHERE (username = $1 )","time":"2021-04-22T09:04:06+03:00","type":"sql"}
{"level":"error","msg":"Coudn't find user [admin]: with error:record not found","time":"2021-04-22T09:04:06+03:00"}
You have new mail in /var/spool/mail/root
[root@stinga log]#

**Comment by shchbo** [comment] 2021-04-25 04:24
when i try to do something else using the homer-app command i get the same error over an over again:
{"level":"error","msg":"pq: password authentication failed for user \"postgres\"","time":"2021-04-25T07:07:30+03:00"}
{"level":"error","msg":"Couldn't establish connection. Please be sure you can have correct passwordpq: password authentication failed for user \"postgres\"","time":"2021-04-25T07:07:30+03:00"}
{"level":"error","msg":"Try run: sudo -u postgres psql -c \"ALTER USER postgres PASSWORD 'postgres';\"","time":"2021-04-25T07:07:30+03:00"}
panic: pq: password authentication failed for user "postgres"

**Comment by lmangani** [comment] 2021-04-26 10:25
The issue is clearly with the authentication. Perhaps the key ended up being generated with some invalid char?
Please try to set the postgres password and homer password manually and everything should work just fine.

**Comment by shchbo** [comment] 2021-04-27 12:24
i am sorry for my ignorance but when i run this command in order to change the UI password i dont get errors but i still cant log in due to wrong password
homer-app  -database-root-user=postgres -database-host=localhost -database-root-password=postgres -update-ui-password=password
what am i doing wrong? is this the right command?

**Comment by shchbo** [comment] 2021-05-03 05:01
how can i remove homer including DB so i can install it again using the install script?

**Comment by lmangani** [comment] 2021-07-05 21:03
All available commands are in the readme - if you feel any is missing, let us know. 
Since the issue was not specifically with Homer, I'll close this but feel free to comment if you still need assistance.

**Closed as completed by lmangani** 2021-07-05 21:03 UTC
