### ISSUE TITLE
CentOS 7 RPM Build Failure

### ISSUE THREAD

**Issue by 00Asgaroth00** [sipcapture/homer#210] opened 2017-03-06 17:03 UTC
I am trying to follow the steps to build CentOS 7 rpm's as described in the "Build Custom Packages (advanced)" section in the wiki [here](https://github.com/sipcapture/homer/wiki/Package-Install#-build-custom-packages-advanced)

When it comes to building the rpm, there is a build failure once mock is fired up listed below:

```
INFO: Start: build setup for homer-api-5.0.5-20170306154005.el7.centos.src.rpm
INFO: ENTER ['do'](['bash', '--login', '-c', '/usr/bin/rpmbuild -bs --target x86_64 --nodeps /builddir/build/SPECS/homer-api.spec'], chrootPath='/usr/local/src/homer/build/mock/centos-7-x86_64/root'shell=FalseprintOutput=Falseenv={'LANG': 'en_GB.UTF-8', 'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOSTNAME': 'mock', 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"', 'HOME': '/builddir', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PS1': '<mock-chroot> \\s-\\v\\$ '}gid=135user='mockbuild'timeout=0logger=<mockbuild.trace_decorator.getLog object at 0x1317990>uid=0)
INFO: Finish: build setup for homer-api-5.0.5-20170306154005.el7.centos.src.rpm
INFO: Start: rpmbuild homer-api-5.0.5-20170306154005.el7.centos.src.rpm
INFO: ENTER ['do'](['bash', '--login', '-c', u'/usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/homer-api.spec'], chrootPath='/usr/local/src/homer/build/mock/centos-7-x86_64/root'shell=Falseuid=0env={'LANG': 'en_GB.UTF-8', 'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOSTNAME': 'mock', 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"', 'HOME': '/builddir', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PS1': '<mock-chroot> \\s-\\v\\$ '}gid=135user='mockbuild'timeout=0private_network=Truelogger=<mockbuild.trace_decorator.getLog object at 0x1317990>printOutput=False)
INFO: EXCEPTION: [Error()]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mockbuild/trace_decorator.py", line 89, in trace
    result = func(*args, **kw)
  File "/usr/lib/python2.7/site-packages/mockbuild/util.py", line 578, in do
    raise exception.Error("Command failed. See logs for output.\n # %s" % (command,), child.returncode)
Error: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/homer-api.spec
ERROR: Exception(repo/centos/7/source/homer-api-5.0.5-20170306154005.el7.centos.src.rpm) Config(centos-7-x86_64) 0 minutes 6 seconds
INFO: Results and/or logs in: repo/centos/7/x86_64
ERROR: Command failed. See logs for output.
```
There is a second failure, after the above failure, but, I'm guessing that it may be related to the above error.

I've attached the output of the full build output to this ticket, please let me know if you require any additional info from me to assist getting this issue corrected.

[make_centos-7-x86_64.homer.rpm.txt](https://github.com/sipcapture/homer/files/821878/make_centos-7-x86_64.homer.rpm.txt)

**Comment by kvishnivetsky** [comment] 2017-03-06 17:29
Hi, Asgaroth.
It's seems, that there is an error in "make install, process for package homer-api.
If you have a VM, you may performmake installfor homer-api package and check if a failure appears.

-------- Исходное сообщение --------От: 00Asgaroth00 <notifications@github.com> Дата: 07.03.2017  0:03  (GMT+07:00) Кому: sipcapture/homer <homer@noreply.github.com> Копия: Subscribed <subscribed@noreply.github.com> Тема: [sipcapture/homer] CentOS 7 RPM Build Failure (#210) 
I am trying to follow the steps to build CentOS 7 rpm's as described in the "Build Custom Packages (advanced)" section in the wiki here
When it comes to building the rpm, there is a build failure once mock is fired up listed below:
INFO: Start: build setup for homer-api-5.0.5-20170306154005.el7.centos.src.rpm
INFO: ENTER ['do'](['bash', '--login', '-c', '/usr/bin/rpmbuild -bs --target x86_64 --nodeps /builddir/build/SPECS/homer-api.spec'], chrootPath='/usr/local/src/homer/build/mock/centos-7-x86_64/root'shell=FalseprintOutput=Falseenv={'LANG': 'en_GB.UTF-8', 'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOSTNAME': 'mock', 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"', 'HOME': '/builddir', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PS1': '<mock-chroot> \\s-\\v\\$ '}gid=135user='mockbuild'timeout=0logger=<mockbuild.trace_decorator.getLog object at 0x1317990>uid=0)
INFO: Finish: build setup for homer-api-5.0.5-20170306154005.el7.centos.src.rpm
INFO: Start: rpmbuild homer-api-5.0.5-20170306154005.el7.centos.src.rpm
INFO: ENTER ['do'](['bash', '--login', '-c', u'/usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/homer-api.spec'], chrootPath='/usr/local/src/homer/build/mock/centos-7-x86_64/root'shell=Falseuid=0env={'LANG': 'en_GB.UTF-8', 'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOSTNAME': 'mock', 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"', 'HOME': '/builddir', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PS1': '<mock-chroot> \\s-\\v\\$ '}gid=135user='mockbuild'timeout=0private_network=Truelogger=<mockbuild.trace_decorator.getLog object at 0x1317990>printOutput=False)
INFO: EXCEPTION: [Error()]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mockbuild/trace_decorator.py", line 89, in trace
    result = func(*args, **kw)
  File "/usr/lib/python2.7/site-packages/mockbuild/util.py", line 578, in do
    raise exception.Error("Command failed. See logs for output.\n # %s" % (command,), child.returncode)
Error: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/homer-api.spec
ERROR: Exception(repo/centos/7/source/homer-api-5.0.5-20170306154005.el7.centos.src.rpm) Config(centos-7-x86_64) 0 minutes 6 seconds
INFO: Results and/or logs in: repo/centos/7/x86_64
ERROR: Command failed. See logs for output.

There is a second failure, after the above failure, but, I'm guessing that it may be related to the above error.
I've attached the output of the full build output to this ticket, please let me know if you require any additional info from me to assist getting this issue corrected.
make_centos-7-x86_64.homer.rpm.txt

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/sipcapture/homer","title":"sipcapture/homer","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/sipcapture/homer"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"CentOS 7 RPM Build Failure (#210)"}],"action":{"name":"View Issue","url":"https://github.com/sipcapture/homer/issues/210"}}}

**Comment by 00Asgaroth00** [comment] 2017-03-06 17:43
OK, I tried to run make install in the buildroot for the mock instance and it seems to install fine, here's what I did:

```
cd /usr/local/src/homer/build/mock/centos-7-x86_64/root
chroot $(pwd)
cd /builddir/build/BUILD/homer-api-5.0.5
make install
```
The output of the make install seems OK to me, here is what it looks like:
```
make[1]: Entering directory `/builddir/build/BUILD/homer-api-5.0.5'
make[1]: Nothing to be done for `install-exec-am'.
mkdir -p /var/www/sipcapture/htdocs
cp -r api apidoc /var/www/sipcapture/htdocs/
mkdir -p /etc/kamailio
cp examples/sipcapture/sipcapture.kamailio /etc/kamailio/kamailio-sipcapture.cfg
mkdir -p /etc/logrotate.d
cp examples/sipcapture/sipcapture.logrotated /etc/logrotate.d/sipcapture
mkdir -p /etc/rsyslog.d
cp examples/sipcapture/sipcapture.rsyslogd /etc/rsyslog.d/sipcapture.conf
make[1]: Leaving directory `/builddir/build/BUILD/homer-api-5.0.5'
```

**Comment by 00Asgaroth00** [comment] 2017-03-06 19:31
I just found the mock build.log in the repo directory. I've attached it to this post, I'm wondering if it has something to do with omitting the sql/postgres directory. Here's a snippet of where it fails:

```
+ install -d /builddir/build/BUILDROOT/homer-api-5.0.5-20170306154005.el7.centos.x86_64/var/sipcapture/mysql
+ install -d /builddir/build/BUILDROOT/homer-api-5.0.5-20170306154005.el7.centos.x86_64/usr/share/sipcapture/sql/
+ install -p -m 644 sql/homer_databases.sql sql/homer_user.sql sql/homer_user_bootstrap.sql sql/postgres sql/schema_configuration.sql sql/schema_data.sql sql/schema_statistic.sql /builddir/build/BUILDROOT/homer-api-5.0.5-20170306154005.el7.centos.x86_64/us
r/share/sipcapture/sql/
install: omitting directory 'sql/postgres'
RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.7nRRgI (%install)
    Bad exit status from /var/tmp/rpm-tmp.7nRRgI (%install)
Child return code was: 1
EXCEPTION: [Error()]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mockbuild/trace_decorator.py", line 89, in trace
    result = func(*args, **kw)
  File "/usr/lib/python2.7/site-packages/mockbuild/util.py", line 578, in do
    raise exception.Error("Command failed. See logs for output.\n # %s" % (command,), child.returncode)
Error: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/homer-api.spec
```

Full log attached.


[build.zip](https://github.com/sipcapture/homer/files/822253/build.zip)

**Comment by kvishnivetsky** [comment] 2017-03-07 08:09
It seems, that the problem is in SPEC file %install section.

**Comment by 00Asgaroth00** [comment] 2017-03-07 10:13
Thanks, let me know if you need me to test anything.

**Comment by 00Asgaroth00** [comment] 2017-03-07 19:51
ok, I've managed to get past the postgress error for homer-api. I made the following modifications:

```
diff -u homer-api.spec.in.original homer-api.spec.in
```
```
--- homer-api.spec.in.original  2017-03-07 20:19:26.517802693 +0000
+++ homer-api.spec.in   2017-03-07 20:20:42.616795383 +0000
@@ -131,7 +131,9 @@
 # MySQL configuration
 install -d %{buildroot}%{DBDIR}
 install -d %{buildroot}%{_datadir}/sipcapture/sql/
-install -p -m 644 sql/* %{buildroot}%{_datadir}/sipcapture/sql/
+install -d %{buildroot}%{_datadir}/sipcapture/sql/postgres/
+install -p -m 644 sql/*.sql %{buildroot}%{_datadir}/sipcapture/sql/
+install -p -m 644 sql/postgres/*.sql %{buildroot}%{_datadir}/sipcapture/sql/postgres/
 install -d %{buildroot}%{_sysconfdir}/my.cnf.d
 install -d %{buildroot}%{_sysconfdir}/systemd/system
 install -p -m 644 examples/mysql/sipcapture.cnf %{buildroot}%{_sysconfdir}/my.cnf.d/sipcapture.cnf
```
Now I'm coming across some old scripts that are trying to be installed, but cannot stat them:

```
+ install -p -m 644 scripts/sipcapture.crontab /builddir/build/BUILDROOT/homer-api-5.0.5-20170307202239.el7.centos.x86_64/etc/cron.d/sipcapture
+ install -p -m 644 scripts/homer_rotate /builddir/build/BUILDROOT/homer-api-5.0.5-20170307202239.el7.centos.x86_64/usr/bin/homer_rotate
+ install -p -m 644 scripts/homer_mysql_new_table.pl /builddir/build/BUILDROOT/homer-api-5.0.5-20170307202239.el7.centos.x86_64/usr/bin/homer_mysql_new_table.pl
install: cannot stat 'scripts/homer_mysql_new_table.pl': No such file or directory
RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.cgJ7Om (%install)
    Bad exit status from /var/tmp/rpm-tmp.cgJ7Om (%install)
Child return code was: 1
EXCEPTION: [Error()]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mockbuild/trace_decorator.py", line 89, in trace
    result = func(*args, **kw)
  File "/usr/lib/python2.7/site-packages/mockbuild/util.py", line 578, in do
    raise exception.Error("Command failed. See logs for output.\n # %s" % (command,), child.returncode)
Error: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/homer-api.spec
```
Which scripts are the latest? It looks like "homer_mysql_new_table.pl" is under the "old" directory under scripts.

**Comment by kvishnivetsky** [comment] 2017-03-16 08:40
Hi, Asgaroth.
I made some fixes in homer-api submodule.
Try to build it now, please.

**Comment by 00Asgaroth00** [comment] 2017-03-16 08:47
Ok, I'll spin up a fresh CentOS 7 VM and let you know shortly.

**Comment by 00Asgaroth00** [comment] 2017-03-16 09:14
Hi,

Thanks for the fixes, the build has moved past the homer-[api/ui] phase, but now appears to fail on building captagent. Captagent also appears to build locally on the system and not using the mock environment like homer-ui/homer-api does.

Failure is as follows:

```
checking for bison... bison -y
checking for pthread_create in -lpthread... yes
checking for dlopen in -ldl... yes
checking for XML_ParserCreate in -lexpat... yes
checking for pcap_open_live in -lpcap... yes
checking for json_object_get in -ljson... no
checking for json_object_get in -ljson-c... yes
checking for yywrap in -lfl... yes
configure: checking for LiBUV and Header files...
checking uv.h usability... no
checking uv.h presence... no
checking for uv.h... no
configure: error: uv.h headers not found.
make[3]: *** [captagent.configure] Error 1
make[3]: Leaving directory `/usr/local/src/homer/build'
make[2]: *** [centos-7-x86_64.captagent.rpm] Error 2
make[2]: Leaving directory `/usr/local/src/homer/build'
make[1]: *** [captagent.rpm.if-changed] Error 2
make[1]: Leaving directory `/usr/local/src/homer/build'
make: *** [centos-7-x86_64.homer.rpm] Error 2
```

I've attached the full log file of the commands I run and their output, in-case you need it.

[homer_build.log.1043.txt](https://github.com/sipcapture/homer/files/847181/homer_build.log.1043.txt)

**Comment by 00Asgaroth00** [comment] 2017-03-16 09:26
Just as a heads-up, if I install libuv-devel package on the local system, the captagent configure stage moves past but fails on extracting the captagent tar file, see below:

```
make[2]: Leaving directory `/usr/local/src/homer/build'
checking for changes in captagent...make[2]: Entering directory `/usr/local/src/homer/build'

make[3]: Entering directory `/usr/local/src/homer/build'
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
configure: WARNING: unrecognized options: --disable-dep-check
checking for a BSD-compatible install... /bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '0' is supported by ustar format... yes
"/tmp/homer_build.log.18799" [readonly] 364L, 20054C
make[8]: Leaving directory `/usr/local/src/homer/build/captagent/src/modules/protocol/rtcp/captureplan'
make[7]: Leaving directory `/usr/local/src/homer/build/captagent/src/modules/protocol/rtcp'
 (cd modules/protocol/ss7 && make  top_distdir=../../../../captagent-6.2.0.2 distdir=../../../../captagent-6.2.0.2/src/modules/protocol/ss7 \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[7]: Entering directory `/usr/local/src/homer/build/captagent/src/modules/protocol/ss7'
make[7]: Leaving directory `/usr/local/src/homer/build/captagent/src/modules/protocol/ss7'
 (cd modules/protocol/tcp && make  top_distdir=../../../../captagent-6.2.0.2 distdir=../../../../captagent-6.2.0.2/src/modules/protocol/tcp \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[7]: Entering directory `/usr/local/src/homer/build/captagent/src/modules/protocol/tcp'
make[7]: Leaving directory `/usr/local/src/homer/build/captagent/src/modules/protocol/tcp'
 (cd modules/transport/hep && make  top_distdir=../../../../captagent-6.2.0.2 distdir=../../../../captagent-6.2.0.2/src/modules/transport/hep \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[7]: Entering directory `/usr/local/src/homer/build/captagent/src/modules/transport/hep'
make[7]: Leaving directory `/usr/local/src/homer/build/captagent/src/modules/transport/hep'
 (cd modules/transport/json && make  top_distdir=../../../../captagent-6.2.0.2 distdir=../../../../captagent-6.2.0.2/src/modules/transport/json \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[7]: Entering directory `/usr/local/src/homer/build/captagent/src/modules/transport/json'
make[7]: Leaving directory `/usr/local/src/homer/build/captagent/src/modules/transport/json'
 (cd modules/database/hash && make  top_distdir=../../../../captagent-6.2.0.2 distdir=../../../../captagent-6.2.0.2/src/modules/database/hash \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[7]: Entering directory `/usr/local/src/homer/build/captagent/src/modules/database/hash'
make[7]: Leaving directory `/usr/local/src/homer/build/captagent/src/modules/database/hash'
 (cd modules/database/redis && make  top_distdir=../../../../captagent-6.2.0.2 distdir=../../../../captagent-6.2.0.2/src/modules/database/redis \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[7]: Entering directory `/usr/local/src/homer/build/captagent/src/modules/database/redis'
make[7]: Leaving directory `/usr/local/src/homer/build/captagent/src/modules/database/redis'
 (cd modules/interface/http && make  top_distdir=../../../../captagent-6.2.0.2 distdir=../../../../captagent-6.2.0.2/src/modules/interface/http \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[7]: Entering directory `/usr/local/src/homer/build/captagent/src/modules/interface/http'
make[7]: Leaving directory `/usr/local/src/homer/build/captagent/src/modules/interface/http'
make[6]: Leaving directory `/usr/local/src/homer/build/captagent/src'
 (cd include && make  top_distdir=../captagent-6.2.0.2 distdir=../captagent-6.2.0.2/include \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[6]: Entering directory `/usr/local/src/homer/build/captagent/include'
make[6]: Leaving directory `/usr/local/src/homer/build/captagent/include'
make[5]: Leaving directory `/usr/local/src/homer/build/captagent'
make[4]: Leaving directory `/usr/local/src/homer/build/captagent'
tar (child): captagent/captagent-5.0.5.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
fatal: No names found, cannot describe anything.
Could not find tag v6.0.2
fatal: No names found, cannot describe anything.
Could not find tag 6.0.2
fatal: No names found, cannot describe anything.
Could not find tag v6.0.2
fatal: No names found, cannot describe anything.
Could not find tag 6.0.2
fatal: No names found, cannot describe anything.
Could not find tag v6.0.2
fatal: No names found, cannot describe anything.
Could not find tag 6.0.2
fatal: No names found, cannot describe anything.
Could not find tag v6.0.2
fatal: No names found, cannot describe anything.
Could not find tag 6.0.2
error: File captagent/captagent-6.0.2.tar.gz: No such file or directory
/usr/bin/cat: captagent/captagent-6.0.2.tar.gz: No such file or directory
error: File captagent/captagent-6.0.2.tar.gz: No such file or directory
/usr/bin/cat: captagent/captagent-6.0.2.tar.gz: No such file or directory
error: Failed to read spec file from captagent/captagent-6.0.2.tar.gz
make[3]: *** [captagent.srpm] Error 1
make[3]: Leaving directory `/usr/local/src/homer/build'
make[2]: *** [centos-7-x86_64.captagent.rpm] Error 2
make[2]: Leaving directory `/usr/local/src/homer/build'
make[1]: *** [captagent.rpm.if-changed] Error 2
make[1]: Leaving directory `/usr/local/src/homer/build'
make: *** [centos-7-x86_64.homer.rpm] Error 2
```

**Comment by kvishnivetsky** [comment] 2017-03-16 09:28
You are to install linuv-devel rpm.Do it, please, and start build process again.


Отправлено со смартфона Samsung Galaxy.
-------- Исходное сообщение --------От: 00Asgaroth00 <notifications@github.com> Дата: 16.03.2017  16:14  (GMT+07:00) Кому: sipcapture/homer <homer@noreply.github.com> Копия: "Konstantin S. Vishnivetsky" <reports@vishnivetsky.ru>, Comment <comment@noreply.github.com> Тема: Re: [sipcapture/homer] CentOS 7 RPM Build Failure (#210) 
Hi,
Thanks for the fixes, the build has moved past the homer-[api/ui] phase, but now appears to fail on building captagent. Captagent also appears to build locally on the system and not using the mock environment like homer-ui/homer-api does.
Failure is as follows:
checking for bison... bison -y
checking for pthread_create in -lpthread... yes
checking for dlopen in -ldl... yes
checking for XML_ParserCreate in -lexpat... yes
checking for pcap_open_live in -lpcap... yes
checking for json_object_get in -ljson... no
checking for json_object_get in -ljson-c... yes
checking for yywrap in -lfl... yes
configure: checking for LiBUV and Header files...
checking uv.h usability... no
checking uv.h presence... no
checking for uv.h... no
configure: error: uv.h headers not found.
make[3]: *** [captagent.configure] Error 1
make[3]: Leaving directory `/usr/local/src/homer/build'
make[2]: *** [centos-7-x86_64.captagent.rpm] Error 2
make[2]: Leaving directory `/usr/local/src/homer/build'
make[1]: *** [captagent.rpm.if-changed] Error 2
make[1]: Leaving directory `/usr/local/src/homer/build'
make: *** [centos-7-x86_64.homer.rpm] Error 2

I've attached the full log file of the commands I run and their output, in-case you need it.
homer_build.log.1043.txt

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/sipcapture/homer","title":"sipcapture/homer","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/sipcapture/homer"}},"updates":{"snippets":[{"icon":"PERSON","message":"@00Asgaroth00 in #210: Hi,\r\n\r\nThanks for the fixes, the build has moved past the homer-[api/ui] phase, but now appears to fail on building captagent. Captagent also appears to build locally on the system and not using the mock environment like homer-ui/homer-api does.\r\n\r\nFailure is as follows:\r\n\r\n```\r\nchecking for bison... bison -y\r\nchecking for pthread_create in -lpthread... yes\r\nchecking for dlopen in -ldl... yes\r\nchecking for XML_ParserCreate in -lexpat... yes\r\nchecking for pcap_open_live in -lpcap... yes\r\nchecking for json_object_get in -ljson... no\r\nchecking for json_object_get in -ljson-c... yes\r\nchecking for yywrap in -lfl... yes\r\nconfigure: checking for LiBUV and Header files...\r\nchecking uv.h usability... no\r\nchecking uv.h presence... no\r\nchecking for uv.h... no\r\nconfigure: error: uv.h headers not found.\r\nmake[3]: *** [captagent.configure] Error 1\r\nmake[3]: Leaving directory `/usr/local/src/homer/build'\r\nmake[2]: *** [centos-7-x86_64.captagent.rpm] Error 2\r\nmake[2]: Leaving directory `/usr/local/src/homer/build'\r\nmake[1]: *** [captagent.rpm.if-changed] Error 2\r\nmake[1]: Leaving directory `/usr/local/src/homer/build'\r\nmake: *** [centos-7-x86_64.homer.rpm] Error 2\r\n```\r\n\r\nI've attached the full log file of the commands I run and their output, in-case you need it.\r\n\r\n[homer_build.log.1043.txt](https://github.com/sipcapture/homer/files/847181/homer_build.log.1043.txt)\r\n"}],"action":{"name":"View Issue","url":"https://github.com/sipcapture/homer/issues/210#issuecomment-286998765"}}}

**Comment by 00Asgaroth00** [comment] 2017-03-16 09:29
Hi, sorry, I posted just before you did here, I did install libuv-devel on the local system, but it failued on extracting captagent tar file, see the post above your one :)

**Comment by kvishnivetsky** [comment] 2017-03-17 02:55
This pull request is not merged yet:
https://github.com/sipcapture/homer/pull/211
It fixes this new issue, you had met.

**Closed** 2019-11-28 19:16 UTC
