### ISSUE TITLE
Docker 10 Install Error qryn container is unhealthy

### ISSUE THREAD

**Issue by georghimself** [sipcapture/homer#616] opened 2023-10-05 12:58 UTC
Cheers Guys,

i did a install on Debian 11 but at the end of the Installation
i did get this error message.

Any ideas where to look for problems from here?

root@homer:/home/homer/homer-docker/all-in-one# docker-compose up -d
mailhog is up-to-date
clickhouse-server is up-to-date
alertman is up-to-date
grafana is up-to-date

ERROR: for qryn  Container "9a6480b8c0bb" is unhealthy.
ERROR: Encountered errors while bringing up the project.

**Comment by lmangani** [comment] 2023-10-05 13:04
A good first step is to inspect the container logs to find out what the issue might be. It cannot be guessed by status.

**Comment by georghimself** [comment] 2023-10-05 13:14
ofc. sorrry.
this is the log for clickhouse. im running on proxmox cpu is set to host

Instruction check fail. The CPU does not support SSSE3 instruction set.
Instruction check fail. The CPU does not support SSSE3 instruction set.
Instruction check fail. The CPU does not support SSSE3 instruction set.
Instruction check fail. The CPU does not support SSSE3 instruction set.
/entrypoint.sh: create new user 'qryn' instead 'default'
Instruction check fail. The CPU does not support SSSE3 instruction set.

**Comment by georghimself** [comment] 2023-10-05 13:31
Its an AMD Opteron(tm) Processor 6128 
cpuinfo says flags sse sse2 sse4a
if that helps

**Comment by lmangani** [comment] 2023-10-05 14:00
I guess the issue is with the ClickHouse container not being able to start. 
Since we don't build that container, we can't help much but You can raise this with the ClickHouse team OR switch to a different clickhouse-server distribution (such as those from bitnami, altinity, etc) to replace the default image.

**Comment by lmangani** [comment] 2023-10-06 14:21
Based on the provided info this failure is caused by lack of SS3 instruction set required by ClickHouse (not qryn/homer)

```
Instruction check fail. The CPU does not support SSSE3 instruction set.
```

The solution is to find/use a ClickHouse build w/o SS3 dependencies, if that exists. Closing, but feel free to comment in this thread if you need pointers or suggestions.

**Closed as completed by lmangani** 2023-10-06 14:21 UTC
