### ISSUE TITLE
Docker install can't get data to display.

### ISSUE THREAD

**Issue by xilence222** [sipcapture/homer#449] opened 2021-03-02 16:32 UTC
I've tried about 5 times now with v7 to get data to display in homer webapp.

I've tried with old homer5 repo and data is displayed.

I've pinged loki and db from webapp container and it ping works.

If I go into Grafana and login as admin.
Go to Explore > Label type > sip
I see all the sip traffic stored in Loki

Why does this not show in homer can someone help I would really appreciate it .

**Comment by xilence222** [comment] 2021-03-02 16:33
I'm using the docker-compose inside hom7-prom-all

**Comment by lmangani** [comment] 2021-03-02 17:04
Hey @xilence222 could you paste some examples of your attempts with logs, screenshots or anything we could use to help?

**Comment by xilence222** [comment] 2021-03-02 17:20
This is a new server, only things that I installed is docker. 
This is how I started the application
git clone https://github.com/sipcapture/homer7-docker
  cd homer7-docker/
  cd heplify-server/
  cd hom7-prom-all/
  docker up -d
  
 Output 
 docker-compose up -d
Creating volume "hom7-prom-all_prometheus_data" with default driver
Creating volume "hom7-prom-all_grafana_data" with default driver
Creating prometheus   ... done
Creating loki         ... done
Creating grafana    ... done
Creating alertmanager ... done
Creating db           ... done
Creating nodeexporter   ... done
Creating heplify-server ... done
Creating homer-webapp   ... done

Grafana has data in it..
https://i.imgur.com/B2T8Mc0.png

But when I go to Homer and login with admin/sipcapture
I see nothing https://i.imgur.com/BuxvsuI.png

Here is output from docker logs homer-webapp

 Version: homer-app 1.3.15
⇨ http server started on [::]:80
{"level":"error","msg":"couldn't make ping to [Host: db]: \nsql: database is closed","time":"2021-03-02T17:15:40Z"}
{"level":"error","msg":"couldn't make ping to [Host: db]: \nsql: database is closed","time":"2021-03-02T17:16:40Z"}
{"level":"error","msg":"couldn't make ping to [Host: db]: \nsql: database is closed","time":"2021-03-02T17:17:40Z"}
{"level":"error","msg":"couldn't make ping to [Host: db]: \nsql: database is closed","time":"2021-03-02T17:18:40Z"}
{"level":"error","msg":"couldn't make ping to [Host: db]: \nsql: database is closed","time":"2021-03-02T17:19:40Z"}

I can add users to the webapp, dunno if that proves it can speak to the DB or not.
Also ping works from the webapp container with `ping db`

**Comment by lmangani** [comment] 2021-03-02 17:59
This could be just due to confusion on how search and mapping work. Please try the following:

1 - create a new dashboard with a Search form and a Results Container, call it `OPTIONS Search` or something
2  - configure the search form to use the `SIP- default` mapping schema
![image](https://user-images.githubusercontent.com/1423657/109692957-629b1a00-7b89-11eb-80a8-159b57de9c92.png)

3 - save and search

do you have results?

**Comment by xilence222** [comment] 2021-03-02 19:57
Sorry I still don't see results with that.
https://i.imgur.com/d5UB5z2.png
https://i.imgur.com/2YuraZO.png

**Comment by xilence222** [comment] 2021-03-03 14:02
I wonder if this is a similar issue to #451

**Comment by lmangani** [comment] 2021-03-03 15:53
I just tested this from scratch and I cannot reproduce your issue.

Try sending in a call with `hepgen.js` and see if that shows up:
 ```
npm install -g hepgen.js
hepgen.js -s YOUR_HOMER_IP -p 9060 -c $(npm root -g)/hepgen.js/config/b2bcall_rtcp.js
```

![image](https://user-images.githubusercontent.com/1423657/109832808-01cf1880-7c41-11eb-9990-012aafe17b68.png)

**Comment by xilence222** [comment] 2021-03-04 10:25
I ran that with the existing instance and go no results. Sorry.
I'm gonna trash these containers and try with fresh  👍

**Comment by lmangani** [comment] 2021-07-05 21:07
Closing for no updates. Please reopen if this is still an issue.

**Closed as completed by lmangani** 2021-07-05 21:07 UTC
