### ISSUE TITLE
Homer Stopped working ,NO data in mysql and WEB homer

### ISSUE THREAD

**Issue by bharathg65** [sipcapture/homer#234] opened 2017-06-15 14:58 UTC
HI all ,
Suddenly My HOmer is not showing any data , earlier it was working perfectly .
I didn't done any changes ,but calls are showing in sipgrep -f .
[root@localhost kamailio]# sipgrep -f 5566
interface: enp0s31f6 (192.168.150.0/255.255.255.0)
filter: (ip) and ( portrange 5060-5061) or (udp and ip[6:2] & 0x3fff != 0)
match: (From:|f:) (.*)5566(.*)

U 2017/06/15 10:44:52.541068 192.168.150.16:9060 -> 192.168.150.10:5060

REGISTER sip:192.168.150.10 SIP/2.0.
Via: SIP/2.0/UDP 192.168.150.16:9060;branch=z9hG4bK80ab98f74650e711920c4a65c9369162;rport.
From: "PhonerLite" <sip:5566@192.168.150.10>;tag=545194398.
To: "PhonerLite" <sip:5566@192.168.150.10>.
Call-ID: 80AB98F7-4650-E711-920A-4A65C9369162@192.168.150.16.
CSeq: 75 REGISTER.
Contact: <sip:5566@192.168.150.16:9060>;+sip.instance="<urn:uuid:80491E8A-784F-E711-9684-700D772FB09A>".
Allow: INVITE, ACK, BYE, CANCEL, INFO, MESSAGE, NOTIFY, OPTIONS, REFER, UPDATE, PRACK.
Max-Forwards: 70.
Allow-Events: org.3gpp.nwinitdereg.
User-Agent: SIPPER for PhonerLite.
Supported: replaces, from-change, gruu.
Expires: 900.
Content-Length: 0.

pls find the attached kamailio.cfg and screen short of old capture .

And am just using Kamailio as capture agent .

Any pls suggest me , how to fix this issue .

Regards
Bharath.G

[kamailio config.txt](https://github.com/sipcapture/homer/files/1078024/kamailio.config.txt)
![old data](https://user-images.githubusercontent.com/25815738/27187491-fb79c0ea-5208-11e7-9cae-71f8ba344fa2.JPG)

**Comment by lmangani** [comment] 2017-06-15 15:27
Hi Bharath.

A few suggestions to get started:

* Check if your rotation scripts are still functional, most likely there are errors with the db or the space.
* Check the kamailio logs for errors receiving or inserting the packets.

The trace example you included is confusing tho, HOMER receives on 9060, not 5060 so I'm not sure what that stands for as of yet... doublecheck you are indeed sending traffic to HOMER:9060 from your agents. Nothing from 9060 should be forwarded out and if it is, there's an issue of a different nature.

Hope this helps - as this is not a bug I will close this issue, but will continue helping if needed, although the mailing list is a better place for advice.

**Closed by lmangani** 2017-06-15 15:27 UTC

**Comment by bharathg65** [comment] 2017-06-16 06:45
HI IMANGANI,
Thanks for your suggestion, port 9060 which i used for testing , earlier i used 5060 port only .
 Can you pls guide me , from where(path) i will get below logs ?

Check if your rotation scripts are still functional, most likely there are errors with the db or the space.
Check the kamailio logs for errors receiving or inserting the packets.

Regards
Bharath.G

**Comment by bharathg65** [comment] 2017-06-16 06:49
HI IMANGANI,
Thanks for your suggestion, port 9060 which i used for testing , earlier i used 5060 port only .
Can you pls guide me , from where(path) i will get below logs ?

Check if your rotation scripts are still functional, most likely there are errors with the db or the space.
Check the kamailio logs for errors receiving or inserting the packets.

Regards
Bharath.G



________________________________

**Comment by bharathg65** [comment] 2017-06-16 15:20
HI , still am facing the issue .
can you pls guide me !

[root@localhost log]# tailf kamailio.log
Jun 16 11:14:51 localhost homer[1340]: ERROR: rtimer [rtimer_mod.c:164]: child_init(): failed to start timer routine as process
Jun 16 11:14:51 localhost homer[1340]: ERROR: <core> [sr_module.c:923]: init_mod_child(): Error while initializing module rtimer (//usr/lib/x86_64-linux-gnu/kamailio/modules/rtimer.so)
Jun 16 11:14:51 localhost homer[1340]: ERROR: <core> [main.c:1697]: main_loop(): error in init_child
Jun 16 11:14:51 localhost homer[1339]: ERROR: db_mysql [km_my_con.c:124]: db_mysql_new_connection(): driver error: Can't connect to MySQL server on '127.0.0.1' (111)
Jun 16 11:14:51 localhost homer[1339]: ERROR: <core> [db.c:318]: db_do_init2(): could not add connection to the pool
Jun 16 11:14:51 localhost homer[1339]: ERROR: sipcapture [sipcapture.c:1104]: child_init(): unable to connect to database [mysql://root:Bharath@123@127.0.0.1/homer_data] from capture_mode param.
Jun 16 11:14:51 localhost homer[1339]: ERROR: <core> [sr_module.c:923]: init_mod_child(): Error while initializing module sipcapture (//usr/lib/x86_64-linux-gnu/kamailio/modules/sipcapture.so)
Jun 16 11:14:51 localhost homer[1339]: ERROR: <core> [pt.c:329]: fork_process(): init_child failed for process 8, pid 1339, "secondary timer"
Jun 16 11:14:51 localhost homer[1339]: ERROR: <core> [timer_proc.c:418]: sr_wtimer_start(): wtimer starting failed
Jun 16 11:14:51 localhost homer[1339]: CRITICAL: <core> [main.c:1689]: main_loop(): Cannot start wtimer
