### ISSUE TITLE
Homer stops working after reboot

### ISSUE THREAD

**Issue by i0nviz** [sipcapture/homer#471] opened 2021-06-15 13:35 UTC
Hello.

It's been a few reinstall of my VM because I've tought I did something wrong, but it wasn't the case.

I'm installing it on Debian 9 using the automated script method, and it works great, until the VM is actually rebooted. Then it stops addind data to the database. I can still search for any calls that were written in the DB before the  reboot, so DB access works fine.

Any help would be appreciated
Thanks !

**Comment by lmangani** [comment] 2021-06-15 13:40
We can't unfortunately guess what the issue might be. Please attach all the relevant logs from heplify-server, homer-app, postgres when this happens and we might be able to help further.

**Comment by adubovikov** [comment] 2021-06-16 02:34
I think the issue is because heplify-server lost the connection to your DB. Once you will restart it , you will able to see new packets

**Comment by lmangani** [comment] 2021-07-05 21:00
Closing for no updates. Please reopen if this is still an issue.

**Closed as completed by lmangani** 2021-07-05 21:00 UTC
