### ISSUE TITLE
RTCP Data Missing - GUI issue

### ISSUE THREAD

**Issue by AnonymousMonkey75** [sipcapture/homer#412] opened 2020-08-25 20:36 UTC
I think there is a bug preventing the GUI from showing some QoS (RTCP) data.

I'm running the latest version available via docker, installed via docker about 12 days ago.

I'm able to see bidirectional RTCP data on the PBX<-->SIP trunk provider just fine in the GUI/QoS tab. I'm also to see RTCP data from my PBX to my endpoints in the QoS tab but not endpoints to the PBX.

The RTCP data from the endpoints to the PBX is missing from the GUI. I say it's missing from the GUI only as when I inspect the "qos" section with f12 in Chrome and pull up the call-id, I can see bidirectional data in the f12 debug window but homer itself only shows one direction in the QoS tab.

I've attached a screenshot but it's hard to understand as I blanked out the public IP addresses. I can provided an unmasked screenshot to private addresses as required.

In the screenshot in the network debug window you can see #6 on the right. It is RTCP data for the RTP stream from the my endpoint (phone) to the PBX which is not in the homer QoS tab. I've blocked out my public addresses. #7 on the right is data from the PBX to my endpoint and is represented in the QoS tab on the left of the screenshot. The address ending in 9.18 is where my endpoints are. The address ending in 57.68 is where the PBX is. You can see IP xx.xx.9.18 to xx.xx.57.68 is missing in the gui.

![capture2](https://user-images.githubusercontent.com/8464903/91225144-b9aac880-e6e8-11ea-9151-9956a68963dd.png)

**Comment by adubovikov** [comment] 2020-08-25 21:04
I think the issue has been fixed in the homer-view. @AlexeyOplachko can you please confirm it was back ported to the homer-ui as well ?

**Comment by adubovikov** [comment] 2020-08-25 21:05
@Demolish50 and if you can provide the csv dump of your rtcp table with these rtcp reports, it will help a lot to reproduce the issue in our lab.

**Comment by AnonymousMonkey75** [comment] 2020-08-26 13:18
@adubovikov Sorry, to be clear you want me to export the table from postgres to a CSV? Or do you mean from that Chrome debug somehow?

Sure I can do that, I just need a private way to provide it.

**Comment by AnonymousMonkey75** [comment] 2020-09-24 14:58
I updated with the new docker containers yesterday and saw some nice changes but this issue still exists.

**Comment by lmangani** [comment] 2020-09-24 15:05
@AlexeyOplachko could you take a look when possible?

**Comment by AnonymousMonkey75** [comment] 2020-09-25 13:26
The RTCP data that is not showing in the GUI is generated by Sangoma phones. They generate RTCP XR. I can provide capture if provided private way to provide it.

**Comment by lmangani** [comment] 2020-09-25 15:19
There's `RTCP XR` and `RTCP XR/Vq` - they are not the same - for the latter you can try https://github.com/negbie/heplify-xrcollector

**Comment by AnonymousMonkey75** [comment] 2020-09-28 13:47
> There's `RTCP XR` and `RTCP XR/Vq` - they are not the same - for the latter you can try https://github.com/negbie/heplify-xrcollector

Can you please help me understand. I'm unaware that they are not the same. We are collecting the RTCP XR data as you can see in the debug window or am I misunderstanding? 

I'll try it for giggles but I don't follow.

I tried but I can't have it bind to the same port to listen as it's already bound by heplify.

**Comment by lmangani** [comment] 2020-09-28 13:56
Use a different port. RTCP-XR senders usually feature a different endpoint configuration since they are out-of-band.

**Comment by AnonymousMonkey75** [comment] 2020-09-28 13:58
For the listening port? If I tell it to listen on something other than 5060 I assume it won't capture anything or are you suggesting I need to reconfigure my endpoints. 

"listen udp :5060: bind: address already in use"

**Comment by AnonymousMonkey75** [comment] 2020-09-28 14:15
OK I think I got that all sorted now that I understand. I configured the endpoints to send VQ RTCP data to the system (the PBX) hosting the xrcollector. I used port 8005. The xrcollector is sending data to the server running heplify and everything else. I can see in the log output of the xr collector (./heplify-xrcollector -xs :8005 -hs 10.108.0.2:9060 -hi 5000 -debug) the traffic from the phones and it appears to have sent it over to the heplify server but I still don't see the data in homer. I still see the data from the phones like I always (via debug window in Chrome) have though but it looks like regular RTCP XR data to me or I misunderstand something about publish.  

Before these config changes the phones were only sending RTCP XR as VQ RTCP Report was explicitly disabled on the phone.

**Comment by AnonymousMonkey75** [comment] 2020-09-28 14:27
Here is the RTCP XR data as presented via the chrome bug window.

`2: {captureId: "5000", correlation_id: "5deeb2698fdbf6c@192.168.1.135",…}
captureId: "5000"
correlation_id: "5deeb2698fdbf6c@192.168.1.135"
create_date: "2020-09-28T14:23:55.061131Z"
dbnode: "local"
dstIp: "XX.XX.57.68"
dstPort: 16773
id: 43783
node: ["local", "5000"]
0: "local"
1: "5000"
payloadType: 5
profile: ""
proto: "rtcp"
protocol: 17
protocolFamily: 2
raw: "{"sender_information":{"ntp_timestamp_sec":3810291834,"ntp_timestamp_usec":1975240000,"rtp_timestamp":2687691728,"packets":500,"octets":80000},"ssrc":1856360383,"type":207,"report_count":1,"report_blocks":[{"source_ssrc":0,"fraction_lost":0,"packets_lost":1,"highest_seq_no":12559,"ia_jitter":0,"lsr":0,"dlsr":0}],"report_blocks_xr":{"type":7,"id":0,"fraction_lost":0,"fraction_discard":0,"burst_density":0,"gap_density":0,"burst_duration":0,"gap_duration":10000,"round_trip_delay":0,"end_system_delay":30},"sdes_ssrc":1856360383}"
sid: "5deeb2698fdbf6c@192.168.1.135"
srcIp: "XX.XX.9.18"
srcPort: 12183
timeSeconds: 1601303035
timeUseconds: 61131
3: {captureId: "5000", correlation_id: "5deeb2698fdbf6c@192.168.1.135",…}
4: {captureId: "5000", correlation_id: "5deeb2698fdbf6c@192.168.1.135",…}
5: {captureId: "5000", correlation_id: "5deeb2698fdbf6c@192.168.1.135",…}`

Compared to the one that does show in the GUI, type value is different. This XR is type 7. The working is type 0, if that matters.

**Comment by lmangani** [comment] 2021-07-05 21:12
I see this was never completer or confirmed - is this still an issue which needs assistance?

**Comment by AnonymousMonkey75** [comment] 2021-07-05 22:05
yes it is still broke as of three weeks ago

**Comment by lmangani** [comment] 2021-07-10 19:12
@AlexeyOplachko @RFbkak37y3kIY please reconfirm and fix this issue

**Comment by adubovikov** [comment] 2021-09-01 14:35
Please install homer-app-1.4.0 and test again!

**Comment by adubovikov** [comment] 2021-11-06 13:56
@Demolish50 i will close the ticket. Please reopen if it will be needed

**Closed as completed by adubovikov** 2021-11-06 13:56 UTC
Labels: Testing Needed

**Comment by AnonymousMonkey75** [comment] 2021-12-13 16:01
The issue still persists. 

The only thing I can think of is maybe Homer doesn't like source_ssrc being 0? That is the only difference I can really find. The issue persists as before. Chrome network debug shows the traffic, its just not graphed in homer in the qos tab.
