### ISSUE TITLE
Share link dont works

### ISSUE THREAD

**Issue by qwantanius** [sipcapture/homer#447] opened 2021-02-22 19:14 UTC
1. Open homer
2. Open any message
3. Press share-link and it will throw into a new tab, but without any data

**Comment by adubovikov** [comment] 2021-02-22 20:00
can you record video ? we couldn't reproduce this issue

**Comment by lmangani** [comment] 2021-07-05 21:06
Closing for no updates. Please reopen if this is still an issue.

**Closed as completed by lmangani** 2021-07-05 21:06 UTC
