### ISSUE TITLE
Wrong packets lost calculation

### ISSUE THREAD

**Issue by sfrique** [sipcapture/homer#268] opened 2018-02-06 17:26 UTC
Hello,

We've been using homer for a while and sometimes it shows whats seems to be wrong stats for a call.
He use https://github.com/sipcapture/hepipe.js for stats.

Current config is:
kamailio sending traffic using sip_duplicate and hep.
FS sending using hep as well.

We need help to try figure out what it could be, here are some examples:
![homer-issue3](https://user-images.githubusercontent.com/3711481/35873772-dc24a32e-0b51-11e8-8aad-c88089a80de6.JPG)
![homer-issue2](https://user-images.githubusercontent.com/3711481/35873773-dc5f90f6-0b51-11e8-97bd-e3b8ef418892.JPG)

**Comment by lmangani** [comment] 2018-02-06 22:20
Hi @sfrique you forgot to mention how you send in RTCP statistics being displayed - this is critical towards understanding. Try select the packet-loss and packets series on the chart to see what actually happened and where.

A similar effect is sometimes caused by pre-recorded RTP streams being injected (or ringback audio, etc) poisoning the passive stats with large sequence number jumps, not sure if this might be the case.

**Comment by sfrique** [comment] 2018-02-07 02:04
@lmangani the RTCP statistics are been sent by hepipe.js on freeswitch machine.

Once i get information about the other questions on the chart I post here.

How this pre-recorded RTP could happen? 
Thanks

**Comment by sfrique** [comment] 2018-02-07 12:52
Does this help some how?

this is a pre recorded audio been played on an extension at freeswitch

![screenshot_20180207_10h49m56s](https://user-images.githubusercontent.com/3711481/35917269-a8043958-0bf4-11e8-9afe-022aab3ac958.png)
![screenshot_20180207_10h49m49s](https://user-images.githubusercontent.com/3711481/35917272-a82092b0-0bf4-11e8-8509-33d95f51d416.png)

**Comment by adubovikov** [comment] 2018-02-07 14:13
Nop. You should check RTCP reports and compare it to real RTP traffic. The
RTCP reports come from UAC/UAS and Homer in this case only a collector.

**Comment by sfrique** [comment] 2018-02-07 15:16
I will see if i can get the real RTP traffic.

The number from the report seems the same at homer. So maybe a hepipe of freeswitch problem?


```
Feb  5 12:51:23.358273 fs-1 hepipejs[9002]: Sending HEP3 Packet to bigcouch-3.c.instant-matter-739.internal:9060...
Feb  5 12:51:23.358418 fs-1 hepipejs[9002]: Processing RTCP Report... { headers: 
Feb  5 12:51:23.358489 fs-1 hepipejs[9002]:    [ { name: 'Event-Name', value: 'RECV_RTCP_MESSAGE' },
Feb  5 12:51:23.358572 fs-1 hepipejs[9002]:      { name: 'Core-UUID',
Feb  5 12:51:23.358679 fs-1 hepipejs[9002]:        value: 'a9763527-a534-4d5e-9018-bde4ff9a615a' },
Feb  5 12:51:23.358726 fs-1 hepipejs[9002]:      { name: 'FreeSWITCH-Hostname', value: 'fs-1' },
Feb  5 12:51:23.358802 fs-1 hepipejs[9002]:      { name: 'FreeSWITCH-Switchname', value: 'fs-1' },
Feb  5 12:51:23.358879 fs-1 hepipejs[9002]:      { name: 'FreeSWITCH-IPv4', value: '10.240.0.8' },
Feb  5 12:51:23.358954 fs-1 hepipejs[9002]:      { name: 'FreeSWITCH-IPv6', value: '::1' },
Feb  5 12:51:23.359076 fs-1 hepipejs[9002]:      { name: 'Event-Date-Local', value: '2018-02-05 12:51:23' },
Feb  5 12:51:23.359141 fs-1 hepipejs[9002]:      { name: 'Event-Date-GMT',
Feb  5 12:51:23.359247 fs-1 hepipejs[9002]:        value: 'Mon, 05 Feb 2018 12:51:23 GMT' },
Feb  5 12:51:23.359292 fs-1 hepipejs[9002]:      { name: 'Event-Date-Timestamp', value: '1517835083332575' },
Feb  5 12:51:23.359366 fs-1 hepipejs[9002]:      { name: 'Event-Calling-File', value: 'switch_core_media.c' },
Feb  5 12:51:23.359501 fs-1 hepipejs[9002]:      { name: 'Event-Calling-Function',
Feb  5 12:51:23.359546 fs-1 hepipejs[9002]:        value: 'switch_core_media_read_frame' },
Feb  5 12:51:23.359621 fs-1 hepipejs[9002]:      { name: 'Event-Calling-Line-Number', value: '2380' },
Feb  5 12:51:23.359728 fs-1 hepipejs[9002]:      { name: 'Event-Sequence', value: '423743' },
Feb  5 12:51:23.359770 fs-1 hepipejs[9002]:      { name: 'Unique-ID', value: 'd8c6def9996cf19a' },
Feb  5 12:51:23.359844 fs-1 hepipejs[9002]:      { name: 'SSRC', value: '545f5f63' },
Feb  5 12:51:23.359955 fs-1 hepipejs[9002]:      { name: 'NTP-Most-Significant-Word', value: '3726823883' },
Feb  5 12:51:23.359999 fs-1 hepipejs[9002]:      { name: 'NTP-Least-Significant-Word', value: '1214775665' },
Feb  5 12:51:23.360078 fs-1 hepipejs[9002]:      { name: 'RTP-Timestamp', value: '3223188663' },
Feb  5 12:51:23.360181 fs-1 hepipejs[9002]:      { name: 'Sender-Packet-Count', value: '156' },
Feb  5 12:51:23.360223 fs-1 hepipejs[9002]:      { name: 'Octect-Packet-Count', value: '15279' },
Feb  5 12:51:23.360365 fs-1 hepipejs[9002]:      { name: 'Last-RTP-Timestamp', value: '3223189591' },
Feb  5 12:51:23.360497 fs-1 hepipejs[9002]:      { name: 'RTP-Rate', value: '48000' },
Feb  5 12:51:23.360544 fs-1 hepipejs[9002]:      { name: 'Capture-Time', value: '1517835083350026' },
Feb  5 12:51:23.360619 fs-1 hepipejs[9002]:      { name: 'Source0-SSRC', value: '8aa74fc6' },
Feb  5 12:51:23.360723 fs-1 hepipejs[9002]:      { name: 'Source0-Fraction', value: '4' },
Feb  5 12:51:23.360764 fs-1 hepipejs[9002]:      { name: 'Source0-Lost', value: '768' },
Feb  5 12:51:23.361682 fs-1 hepipejs[9002]:      { name: 'Source0-Loss-Avg', value: '1' },
Feb  5 12:51:23.361877 fs-1 hepipejs[9002]:      { name: 'Source0-Highest-Sequence-Number-Received',
Feb  5 12:51:23.362026 fs-1 hepipejs[9002]:        value: '5699' },
Feb  5 12:51:23.362145 fs-1 hepipejs[9002]:      { name: 'Source0-Jitter', value: '310' },
Feb  5 12:51:23.362191 fs-1 hepipejs[9002]:      { name: 'Source0-LSR', value: '0' },
Feb  5 12:51:23.362299 fs-1 hepipejs[9002]:      { name: 'Source0-DLSR', value: '0' } ],
Feb  5 12:51:23.362486 fs-1 hepipejs[9002]:   hPtr: null,
Feb  5 12:51:23.362521 fs-1 hepipejs[9002]:   type: 'RECV_RTCP_MESSAGE',
Feb  5 12:51:23.362657 fs-1 hepipejs[9002]:   subclass: undefined,
Feb  5 12:51:23.362707 fs-1 hepipejs[9002]:   body: '' }
Feb  5 12:51:23.362811 fs-1 hepipejs[9002]: {"type":200,"ssrc":"545f5f63","report_count":423743,"report_blocks":[{"source_ssrc":"8aa74fc6","fraction_lost":4,"packets_lost":768,"highest_seq_no":5699,"lsr":0,"ia_jitter":310,"dlsr":0}],"sender_information":{"packets":156,"ntp_timestamp_sec":3726823883,"ntp_timestamp_usec":1214775665,"rtp_timestamp":3223188663,"octets":15279}}
```

**Comment by adubovikov** [comment] 2018-02-07 15:26
sorry, but I try to understand, why it should be a problem of HEPIPE ? Here
you really clear can see:

Feb  5 12:51:23.362811 fs-1 hepipejs[9002]:
{"type":200,"ssrc":"545f5f63","report_count":423743,"report_blocks":[{"source_ssrc":"8aa74fc6","fraction_lost":4,*"packets_lost":768,*"highest_seq_no":5699,"lsr":0,"ia_jitter":310,"dlsr":0}],"sender_information":{"packets":156,"ntp_timestamp_sec":3726823883,"ntp_timestamp_usec":1214775665,"rtp_timestamp":3223188663,"octets":15279}}


What else do you need ? Your UAC has packet lost.

Wbr,
Alexandr

**Comment by sfrique** [comment] 2018-02-07 15:37
So, the `packets: 156` mean what exactly? This is total pkts? 

The question is more like, how we have an avg pkts loss of 492%
I know my UAC has packet loss,  we just want to be able to trust and understand the numbers.

Sorry about the question, I passing information from others that work with me.

Thanks

**Comment by adubovikov** [comment] 2018-02-07 15:44
https://tools.ietf.org/html/rfc3550#section-6.4.1

768 packets has been lost, 156 has been received.

**Comment by lmangani** [comment] 2018-02-07 16:03
Hope this helps. Closing as non issue, HOMER told the truth ;)

**Closed by lmangani** 2018-02-07 16:03 UTC

**Comment by murzic4** [comment] 2018-02-08 12:38
sorry my incompetence but I always assumed:
total number of packets = number of packet received + number of packets lost = 100% = 156 + 768 = 924
% of successfully received packets = (number of packet received / total number of packets) x 100% = 156 / 924 x 100 % = ~16,88% 
% of packets lost = (number of packets lost / total number of packets) x 100% = 768 / 924 x 100 % = ~83,12%

most likely now we have the following formula in homer:
% of packets lost = number of packets lost / number of packet received x 100% = 768/156 x 100% = ~492%
As far as I understand 492% of packets lost means that we lost in 5 times pakets more than we totally have sent, that can not be accepted by my mind

could you please correct me if im wrong?

Thanks in advance,
Sergey

**Comment by lmangani** [comment] 2018-02-08 13:59
@murzic4 there is no logic at play here, the reports come from the UA and HOMER is just assuming they are accurate - this being said I assume you know not all involved parameters are expressed singularly in all circumstances (total packets expected should be used, in this case to estimate % of loss, but sometimes loss is already expressed as a percentage, and so on) and not every vendor respects standards 100% - HOMER falls passively in the middle, where exceptions exist. This being said, the representation is purely a matter of UI JS and not the core, a place where PRs are more than welcome with additions, corrections, conditional functions and whatever else suitable as long as globally useful.

**Comment by platoest** [comment] 2018-02-08 15:26
I tried to look as you suggested into RTCP packet and found that hepipejs sending some strange number for packets_lost which doesn't correspond to what is in RTCP packet:
`Frame 8994: 106 bytes on wire (848 bits), 106 bytes captured (848 bits)
Ethernet II, Src: 42:01:0a:f0:00:01 (42:01:0a:f0:00:01), Dst: 42:01:0a:f0:00:08 (42:01:0a:f0:00:08)
Internet Protocol Version 4, Src: 45.55.32.236, Dst: 10.240.0.8
User Datagram Protocol, Src Port: 38831, Dst Port: 27919
Real-time Transport Control Protocol (Sender Report)
    10.. .... = Version: RFC 1889 Version (2)
    ..0. .... = Padding: False
    ...0 0001 = Reception report count: 1
    Packet type: Sender Report (200)
    Length: 12 (52 bytes)
    Sender SSRC: 0x3e4fbf55 (1045413717)
    Timestamp, MSW: 3727041538 (0xde262402)
    Timestamp, LSW: 1538882487 (0x5bb97bb7)
    [MSW and LSW as NTP timestamp: Feb  8, 2018 01:18:58.358298999 UTC]
    RTP timestamp: 669557136
    Sender's packet count: 275
    Sender's octet count: 32493
    Source 1
        Identifier: 0x8aaaa1fa (2326438394)
        SSRC contents
            Fraction lost: 125 / 256
            Cumulative number of packets lost: 124
        Extended highest sequence number received: 2444
        Interarrival jitter: 1850
        Last SR timestamp: 0 (0x00000000)
        Delay since last SR timestamp: 0 (0 milliseconds)
Real-time Transport Control Protocol (Source description)
[RTCP frame length check: OK - 64 bytes]`

And here is the log which is from hepipejs:
`February 8th 2018, 01:18:59.136    <14>1 2018-02-08T01:18:59.136162802Z fs-1 hepipejs 9002 - - {"type":200,"ssrc":"3e4fbf55","report_count":686648,"report_blocks":[{"source_ssrc":"8aaaa1fa","fraction_lost":125,"packets_lost":31744,"highest_seq_no":2444,"lsr":0,"ia_jitter":1850,"dlsr":0}],"sender_information":{"packets":275,"ntp_timestamp_sec":3727041538,"ntp_timestamp_usec":1538882487,"rtp_timestamp":669557136,"octets":32493}}`

So I assume that Homer UI showing what it's receiving. But hepipejs sending not what's in RTCP packet. So that's not UA issue but something wrong with hepipejs or maybe Freeswitch giving it wrong data.

Could you please tell us if it possible to verify who is really to blame for this?

**Comment by platoest** [comment] 2018-02-08 15:44
The other problem which seems to me a UI issue (or might be a configuration) is that it sums up all data which is received in RECV_RTCP_MESSAGE. RTCP data which is represented in UI should be plainly taken from latest RTCP message:
![image](https://user-images.githubusercontent.com/36237873/35982095-fd131b4c-0cff-11e8-8c20-617b27497def.png)
